---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: testwithrhtap-sept30
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testwithrhtap-sept30 
  name: testwithrhtap-sept30
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi