apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testwithrhtap-sept30
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testwithrhtap-sept30 
  name: testwithrhtap-sept30
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: testwithrhtap-sept30 
